### ISSUE TITLE
the mod doesnt let the game load

### ISSUE THREAD

**Issue by the-mod-doesnt-work-on-client** [MisterNorwood/Hbm-s-Nuclear-Tech-CE#392]
<img width="546" height="346" alt="Image" src="https://github.com/user-attachments/assets/2b03181a-f759-400d-b97f-abfda00bbfcb" />

[crash-2025-08-07_20.23.47-client.txt](https://github.com/user-attachments/files/21671834/crash-2025-08-07_20.23.47-client.txt)

fix ples broda

**Comment by MisterNorwood** [comment]
> no i didnt make another account

sigh...
I pushed an emergency fix in c515ecc507a5a4bf05c40dc8d405d8f48d48fa7b, see if it helps, check log for any errors that stem from QMAWLoader

**Comment by it-dont-work-with-resource-packs** [comment]
[crash-2025-08-07_21.00.23-client.txt](https://github.com/user-attachments/files/21672191/crash-2025-08-07_21.00.23-client.txt)

still doesnt work

(it only fails to load when i got my resource pack active)

**Comment by MisterNorwood** [comment]
00a51604c69618178ef8f4568074458554702765 should fix it
